### ISSUE TITLE
Replace the fasttext requirement

### ISSUE THREAD

**Issue by jdchoi77** [elitcloud/elit#20]
Remove the following fasttext library:
```
pip install fasttext
```
and add the requirement for the following:

https://github.com/facebookresearch/fastText/tree/master/python

**Comment by imgarylai** [comment]
Fix in 91157ecacc18a5da5d89b35aa9cd3d68719a4580

**Comment by imgarylai** [comment]
@ZhengzheYang. We upgrade the fasttext to the latest version from fb.
