### ISSUE TITLE
Path should be passed to Embedding 

### ISSUE THREAD

**Issue by imgarylai** [elitcloud/elit#28]
https://github.com/elitcloud/elit/blob/2840f0de508387be18b1bd00c93dbff0f293bfc4/elit/nlp/tagger/sequence_tagger_model.py#L173-L183

Since elit can be installed through `pip` or run on server, the word embedding path is not always in the same directory of project.

**Comment by imgarylai** [comment]
I added a hotfix for temporarily sol.

**Comment by hankcs** [comment]
Yes, I'll store that information along with model file.
