### ISSUE TITLE
gpu config should be explicitly 

### ISSUE THREAD

**Issue by imgarylai** [elitcloud/elit#30]
https://github.com/elitcloud/elit/blob/879119955a0abaf91f9d5cc20e901aeaf8aef72b/elit/nlp/tagger/mxnet_util.py#L24-L34

We run models on a multi-gpus server, and each model use its gpu. In this case, we can't specify which gpu is gonna to be used outside this project.

**Comment by hankcs** [comment]
Now we can specify a particular device, eg. `tagger = POSTagger(context=mx.gpu(3))`.
