### ISSUE TITLE
ImportError 

### ISSUE THREAD

**Issue by Jeevi10** [elitcloud/elit#37]
ImportError                               Traceback (most recent call last)
<ipython-input-110-d9fea8097eea> in <module>
----> 1 from elit.component import EnglishTokenizer
      2 from elit.component import EnglishMorphAnalyzer
      3 from elit.component import POSFlairTagger
      4 from elit.component import NERFlairTagger
      5 from elit.component import DEPBiaffineParser

ImportError: cannot import name 'EnglishTokenizer' from 'elit.component' (/home/jeev/anaconda3/lib/python3.7/site-packages/elit/component/__init__.py)

​

## Specifications

  - Version:18.04
  - Platform:ubuntu
  - Subsystem:

**Comment by hankcs** [comment]
Hi, the doc is outdated. Plz use `from elit.component.tokenizer import EnglishTokenizer` instead.
I'll fix it in the next release.

**Comment by Jeevi10** [comment]
> from elit.component.tokenizer import EnglishTokenizer

It worked, Thank you so much.
